#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Media.Resource", IsApplication=true)]

namespace Android_Media
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int quran = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int whilebackground = 2130771970;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020004
			public const int buPause = 2130837508;
			
			// aapt resource value: 0x7F020006
			public const int bustart = 2130837510;
			
			// aapt resource value: 0x7F020005
			public const int buStop = 2130837509;
			
			// aapt resource value: 0x7F020000
			public const int Image = 2130837504;
			
			// aapt resource value: 0x7F020007
			public const int linearLayout1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int listView1 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int seekBar1 = 2130837513;
			
			// aapt resource value: 0x7F020001
			public const int Text = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Text1 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Text2 = 2130837507;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Recities = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
